'use strict';

const fs = require('fs');
const exec = require('child_process').exec;
const showColor = require('../lib/showColor');
const path = require('path');

module.exports = function installCommand(program) {
  program
    .command('palette-swap <image> <palette> <outdir>')
    .description('Replaces colors in an image based on a palette file generated by image-colors.')
    .action((image, palette, outdir) => {
      let conf = JSON.parse(fs.readFileSync(palette));
      let promises = [];

      for(let i = 0;i < conf.length; i++) {
        let file = path.resolve(outdir,
          path.basename(image).replace(/(\.[a-z]{1,4})$/, '-'+i+'$1')
        );

        let operations = ['convert', image];
        let fields = Object.keys(conf[i]);
        console.log('Creating '+file+' from '+image);
        for(let j = 0; j < fields.length; j++) {
          let before = fields[j];
          let after = conf[i][before];
          console.log(showColor(before), '->', showColor(after));

          operations.push('\\( -fill "#'+after+'" -opaque "#'+before+'" \\)');
        }
        operations.push(file);

        promises.push(new Promise((resolve, reject) => {
          exec(operations.join(' '), function (err, stdout, stderr) {
            resolve();
          });
        }));
      }

      Promise.all(promises).then(() => {
        // Done.
      });
    });
}