'use strict';

module.exports = function installCommand(program) {
  program
    .command('serve')
    .allowUnknownOption()
    .description('Replaces colors in an image based on a palette file generated by image-colors.')
    .action((image, palette, outdir) => {
      process.argv.splice(process.argv.indexOf('serve'), 1);
      require('.bin/http-server');
    });
}